More complete pre-push hooks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -7,9 +7,20 @@
 set -e
 cd "$(git rev-parse --show-toplevel)"
 
+# fail with uncommitted changes - porcelain output will be empty if good to go
+if git status --porcelain | grep -q .; then
+    printf 'Uncommitted changes!\n' >&2
+    exit 1
+fi
+
+# ensure formatted
+cargo fmt --check
+# run general test suite
 cargo test
+# check for clippy issues
 cargo clippy --tests -- -D warnings
 
+# test all single-backend builds one-by-one
 for backend in arm64 s390x x86_64; do
     cargo clippy --no-default-features --features "$backend" -- -D warnings
 done
